@jwt =


### PRODUCTS CREATE
POST http://localhost:3000/products
content-type: application/json

{
   "name": "keyboard",
   "price": 60,
   "image_url": "keyboard.jpg",
   "description": "A mechanical keyboard"
}
### PRODUCTS INDEX
GET http://localhost:3000/products.json?category=Electronics

### PRODUCTS SHOW
GET http://localhost:3000/products/1.json
Authorization: Bearer

### PRODUCTS UPDATE
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
   "supplier_id": "1"
}
### PRODUCTS DESTROY
DELETE http://localhost:3000/localhost:3000/products/1

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### orders create
POST http://localhost:3000/orders.localhost:3000/users.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "user_id": 1,
  "product_id": 1,
  "quantity": 1,
  "subtotal": 10,
  "tax": ,
  "total":
}

### ORDERS INDEX
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}

